variables:
- name: vEnvironment
  value: DevAdvance2

- name: condition
  value: |
    or
    (
      in(dependencies.Build.result, 'Succeeded', 'SucceededWithIssues', 'Skipped'),
      succeeded()
    )
- name: vEnv
  value: DevAdv2

- name: DevOpsEnv
  value: az-summit-2023-env-applications

- name: SiteName
  value: DevAdv2ServerApp2

- name: SiteRoot
  value: C:\Data\www\DevAdv2ServerApp2

- name: Bindings
  value: |
    {"bindings":
     [
      {
        "protocol": "http",
        "ipAddress": "All Unassigned",
        "port": "7501",
        "hostname": ""
      }
     ]
    }

# https://docs.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops
- name: azureServiceConnection
  value: devops-nonprod

# short kv name, no typo here
- name: KeyVaultName
  value: Kv-nonprod